feat: :sparkles: develop a list product function, a list product DTO,…
ineBallardin/clean_arch_fc pull request #4
Opened 2023-12-28 14:50 UTC by ineBallardin

… unit and integration tests

#2

2023-12-28 16:58 UTC, arthurazevedofranca commented on src/usecase/product/list/list.product.integration.spec.ts
> +        expect(output.products[0].id).toBe(product1.id);
nao seria melhor comparar o objeto inteiro? ver se o primeiro é igual o product1 e o ultimo product2 ?  acho que pode melhorar os nomes dos mocks tambem

2023-12-28 17:00 UTC, arthurazevedofranca commented on src/usecase/product/list/list.product.dto.ts
> +export interface InputListProductDto { }
pq criou essa interface vazia? sendo que o input nem é usado de verdade dentro do usecase

2023-12-28 17:05 UTC, arthurazevedofranca requested changes

2023-12-28 17:05 UTC, arthurazevedofranca commented on src/usecase/product/list/list.product.unit.spec.ts
> +const product1 = ProductFactory.create(
pq que no outro teste voce criou os mocks dentro do it e nesse criou fora? eu acho melhor dentro do it para ficar dentro do ciclo de vida do jest e tambem para valer com AAA arrange, act e assert

2023-12-28 17:05 UTC, arthurazevedofranca commented on src/usecase/product/list/list.product.unit.spec.ts
> +        expect(output.products[0].id).toBe(product1.id);
aqui poderia comparar com o objeto, acho que fica mais legivel ainda mais usando todos os atributos como esta

2023-12-28 17:05 UTC, arthurazevedofranca commented on src/usecase/product/list/list.product.usecase.ts
> +    async execute(input: InputListProductDto): Promise<OutputListProductDto> {
pode tirar o input,nao eh usado

2023-12-28 17:05 UTC, arthurazevedofranca commented on src/usecase/product/list/list.product.usecase.ts
> +    static toOutput(product: Product[]): OutputListProductDto {
esse cara merece um teste. Se for passado undefined ou null o product vai dar erro. Alias pode mudar o nome para products ?

2023-12-28 17:14 UTC, ineBallardin commented on src/usecase/product/list/list.product.dto.ts
> +export interface InputListProductDto { }
Pras implementações futuras. Acha q devo me preocupar com isso lá na frente e deixar sem agr?

2023-12-28 17:16 UTC, ineBallardin commented on src/usecase/product/list/list.product.unit.spec.ts
> +const product1 = ProductFactory.create(
Na verdade eu nem lembro kkkk 😅
Acho q eu tava vendo se dava certo ou algo nesse sentido. O Wesley fez os dele tudo fora se não me engano. Mas vou testar deixar tudo dentro pra ver qlé.

2023-12-28 17:17 UTC, arthurazevedofranca commented on src/usecase/product/list/list.product.dto.ts
> +export interface InputListProductDto { }
acho ue, é codigo morto

2023-12-29 15:19 UTC, ineBallardin commented on src/usecase/product/list/list.product.usecase.ts
> +    async execute(input: InputListProductDto): Promise<OutputListProductDto> {
Lembrei kkkkk
Se eu remover o código "morto" `export interface InputListProductDto { }` do [list.product.dto.ts](https://github.com/ineBallardin/clean_arch_fc/pull/4/files/3aaaa81b8e4f92177294581e1c49eef03c13c04a#diff-329a9b0f534df7721f510d9bd6a549b8b4d6581f9bff0b0d01289a232caa12c4) e remover o `input` de executar aqui, eu não poderia utilizar o DTO nos testes, pois eles executam esse "input" aqui `const output = await productUsecase.execute({});` e nesse módulo preciso utilizar os DTOs.

Mas, tendo em vista que realmente ele não faz diferença nenhuma na execução (pelo menos por enquanto), eu removi igual e vou tentar mandar o desafio sem pra ver qualé, qq coisa eu add novamente.

2023-12-29 15:33 UTC, ineBallardin commented on src/usecase/product/list/list.product.usecase.ts
> +    static toOutput(product: Product[]): OutputListProductDto {
Eu devo criar um arquivo separado para testar ou posso incluir dentro dos arquivos de testes q já tenho?

2023-12-29 15:33 UTC, arthurazevedofranca commented on src/usecase/product/list/list.product.usecase.ts
> +    static toOutput(product: Product[]): OutputListProductDto {
me surpreenda

2023-12-29 15:47 UTC, ineBallardin commented on src/usecase/product/list/list.product.usecase.ts
> +    static toOutput(product: Product[]): OutputListProductDto {
Resolvi utilizar os mesmos arquivos, não vejo motivo pra criar arquivos separados pra testes que estão testando a mesma "funcionalidade". 
## Aí me deparei com mais uma questão:
Eu ia fazer dessa forma, criando 2 `describe`:
```
describe("Unit test for listing products use case", () => {
    it("should list products", async () => {
        códiguinho...
    });
});

describe("Unit test for OutputMapper in listing products use case", () => {
    it("should throw an error when products is undefined", async () => {
                códiguinho...
    });

    it("should throw an error when products is null", async () => {
        códiguinho...
    });
});
```

Mas como são dois `it` tão pequenos resolvi fazer tudo dento do mesmo `describe`.

## Aí fiquei com mais uma dúvida: 
ao invés de fazer assim:
```
    it("should throw an error when products is undefined", async () => {
                códiguinho...
    });

    it("should throw an error when products is null", async () => {
        códiguinho...
    });
```
Pq não fazer assim:
```
    it("should throw an error when products is undefined or null", async () => {
            códiguinho...
    });
```

Então optei pela última opção.

2023-12-29 17:34 UTC, arthurazevedofranca commented on src/usecase/product/list/list.product.usecase.ts
> +    static toOutput(product: Product[]): OutputListProductDto {
qual o conceito de describe para vc?

2023-12-29 17:45 UTC, ineBallardin commented on src/usecase/product/list/list.product.usecase.ts
> +    static toOutput(product: Product[]): OutputListProductDto {
pra indicar o que está sendo testado.
É né? kkkk. Aí cada `it` serve p indicar q tipo de erro tá tratando. É isso?

2023-12-29 17:47 UTC, ineBallardin commented on src/usecase/product/list/list.product.usecase.ts
> +    static toOutput(product: Product[]): OutputListProductDto {
"describe" é usado para organizar e agrupar testes que compartilham um contexto ou condição comum.

2023-12-29 17:54 UTC, arthurazevedofranca commented on src/usecase/product/list/list.product.usecase.ts
> +    static toOutput(product: Product[]): OutputListProductDto {
olha ela tentando ser didatica!  Mas vamos la foi um bom exercicio nao foi?
mas por partes nao vejo problema a validacao estando dentro do mapper.
E mapper eh mapper ne? imagina ele evoluindo e crescendo? imagina no paradigma funcional como ficaria? eu optaria um describe so para ele mesmo com um it so, pq mapper eh diferente do usecase ne? sao contextos diferentes, responsabilidades diferentes, testes untiarios diferentes 👿

2023-12-29 18:27 UTC, ineBallardin commented on src/usecase/product/list/list.product.usecase.ts
> +    static toOutput(product: Product[]): OutputListProductDto {
Eu tentei kkkkk. 
Mas foi um bom exercício simm. Curti p caramba. Então vou alterar pra primeira opção, q era um `describe` só p ele.

2023-12-31 18:21 UTC, arthurazevedofranca approved these changes

2023-12-31 18:42 UTC, merged