feat: :sparkles: implement update product function, DTO, unit and int…
ineBallardin/clean_arch_fc pull request #6
Opened 2023-12-28 16:33 UTC by ineBallardin

…egration tests

Resolve issue: #3

2023-12-28 17:16 UTC, arthurazevedofranca requested changes

2023-12-28 17:16 UTC, arthurazevedofranca commented on src/usecase/product/update/update.product.integration.spec.ts
> +        const productUsecase = new UpdateProductUseCase(productRepository);
acho importante mudar o nome da variavel, productUseCase ta mto generico. pode ser updateProduct sem usecase que induz melhor quem esta lendo

2023-12-28 17:16 UTC, arthurazevedofranca commented on src/usecase/product/update/update.product.integration.spec.ts
> +        expect(output).toEqual(input);
acho que o assert verificando se foi atualizado na base meesmo, nao so confiando no retorno do usecase

2023-12-28 17:16 UTC, arthurazevedofranca commented on src/usecase/product/update/update.product.unit.spec.ts
> +        expect(output).toEqual(input);
falta assert verificando se os metodos mockados foram chamados mesmo ja que eh um teste unitario

2023-12-28 17:16 UTC, arthurazevedofranca commented on src/usecase/product/update/update.product.usecase.ts
> +        await this.ProductRepository.update(product);
esse update ja nao deveria retornar o objeto atualizado?

2023-12-28 17:16 UTC, arthurazevedofranca commented on src/usecase/product/update/update.product.usecase.ts
> +        product.changeName(input.name);
me parece mais um patch aqui doq um update de tudo ne, se fosse para tudo iria fazer um update where by id e setando todos os valores que vieram

2023-12-29 17:08 UTC, ineBallardin commented on src/usecase/product/update/update.product.usecase.ts
> +        await this.ProductRepository.update(product);
Na vdd o `ProductRepository` foi feito pra não retornar nenhum valor por padrão. O Wesley até explica o pq em uma das aulas, mas eu esqueci, vou procurar essa aula de nv pra revisar o pq. Veja como foi feita a [interface](https://github.com/ineBallardin/clean_arch_fc/blob/main/src/domain/product/repository/product-repository.interface.ts).

2023-12-29 17:12 UTC, ineBallardin commented on src/usecase/product/update/update.product.usecase.ts
> +        product.changeName(input.name);
@arthurazevedofranca sim, pelo q me lembro das aulas é só pra atualizar os campos q forem passados através do `input` msm, não tendo a necessidade de passar todos os campos sempre q for atualizar algum campo. Se não me engano é algo nessa linha, mas vou procurar a aula pra ter certeza.

2023-12-29 17:36 UTC, arthurazevedofranca requested changes

2023-12-29 17:36 UTC, arthurazevedofranca commented on src/usecase/product/update/update.product.usecase.ts
> +        await this.ProductRepository.update(product);
ai complica ne ZZzzzzz

2023-12-29 17:36 UTC, arthurazevedofranca commented on src/usecase/product/update/update.product.usecase.ts
> +        product.changeName(input.name);
entao, muda para um update especifico, mto mais performatico. Nao?

2023-12-29 18:06 UTC, ineBallardin commented on src/usecase/product/update/update.product.usecase.ts
> +        product.changeName(input.name);
@arthurazevedofranca se vc diz deve ser. Mas como essa foi uma implementação do Wesley, não sei se eu mecher agr pode afetar o que ele pretende fazer no projeto daqui p frente.

2023-12-29 18:21 UTC, ineBallardin commented on src/usecase/product/update/update.product.usecase.ts
> +        await this.ProductRepository.update(product);
simmm

2023-12-31 18:23 UTC, arthurazevedofranca commented on src/usecase/product/update/update.product.usecase.ts
> +        product.changeName(input.name);
Tá valendo! Vou marcar como resolve mas vou cobrar nos próximos PRs

2023-12-31 18:24 UTC, arthurazevedofranca commented on src/usecase/product/update/update.product.usecase.ts
> +        await this.ProductRepository.update(product);
Outro trecho que vou dar resolve mas vou cobrar nos próximos PRs

2023-12-31 18:24 UTC, arthurazevedofranca approved these changes

2023-12-31 18:56 UTC, merged