feat: :sparkles: Implemented end-to-end automated testing for the API…
ineBallardin/clean_arch_fc pull request #8
Opened 2023-12-31 20:21 UTC by ineBallardin

…'s product listing functionality

Related to issue: #7

2024-01-02 13:20 UTC, arthurazevedofranca requested changes

2024-01-02 13:20 UTC, arthurazevedofranca commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +        expect(listProductsResponseXML.text).toContain(`<?xml version="1.0" encoding="UTF-8"?>`);
acho que ficou ilegivel esse teste. Nao seria melhor fazer igual fez o teste de baixo comparando ja um string completo do xml?

2024-01-02 13:20 UTC, arthurazevedofranca commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +    it("should list all products", async () => {
acho que aqui pode melhorar tanto o texto como implementacao no geral. Revendo aqui entendi que vc quer testar a lista completa em dois tipos de output e ver se estao iguais certo?
acho que pode mudar o texto do it e o teste com dois simples asserts comparando json esperado e xml esperado

2024-01-02 13:20 UTC, arthurazevedofranca commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +const PRODUCT_NAME_A = "Product A";
pq ficaram fora do describe? sendo que so sao usados no describr de products e nao é usado no describe do presenter

2024-01-02 13:20 UTC, arthurazevedofranca commented on src/infrastructure/api/presenters/products.presenter.ts
> +                {
para ficar mais legivel eu deixaria products em uma variavel separada e deixando o `toXML(variavel_criada, xmlOptions)` sendo muito mais legivel essa chamada

2024-01-02 13:20 UTC, arthurazevedofranca commented on src/infrastructure/api/presenters/products.presenter.ts
> +    static listXML(data: OutputListProductsDto): string {
nao vai ter teste unitario nao? mockando o toXML

2024-01-02 13:20 UTC, arthurazevedofranca commented on src/infrastructure/api/presenters/products.presenter.ts
> +    static listXML(data: OutputListProductsDto): string {
e ainda estou em duvida no design aqui definido do presenter com um listXML

2024-01-02 13:20 UTC, arthurazevedofranca commented on src/infrastructure/api/routes/products.route.ts
> +        xml: async () => res.send(ProductsPresenter.listXML(output))
aqui de novo, pq tenho um presenter q tem um listxml e nao tem para json? ou entao eu faco um productsPresenterXML ou dou a responsabilidade de fato para ele do presenter todo incluindo o json

2024-01-02 13:20 UTC, arthurazevedofranca commented on src/infrastructure/api/routes/products.route.ts
> +    const listProducts = new ListProductUseCase(new ProductRepository());
nao vai usar singleton p repository? ta instanciando em toda rota tanto aqui como no post acima

2024-01-02 13:20 UTC, arthurazevedofranca commented on src/infrastructure/api/routes/products.route.ts
> +    const products = new CreateProductUseCase(new ProductRepository());
ja nao deveria ter o usecase como dependencia?

2024-01-02 13:20 UTC, arthurazevedofranca commented on src/infrastructure/api/routes/products.route.ts
> +export const productsRoute = express.Router();
levando em consideracao paradigma funcional e imutavel nao acha code smell esse router aqui solto? ele vai ser criado uma vez no import ficando com seu ciclo de vida dependente do modulos do node.

Nao seria melhor criar uma funcao com suas devidas dependencias onde ela retornar um express.Router? e la onde eh usado de fato cria a rota e associa ao path?

2024-01-02 21:39 UTC, ineBallardin commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +    it("should list all products", async () => {
@arthurazevedofranca isso. Ok :heavy_check_mark:

2024-01-02 23:26 UTC, ineBallardin commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +        expect(listProductsResponseXML.text).toContain(`<?xml version="1.0" encoding="UTF-8"?>`);
Eu não sei como fazer isso kkkkkkk, não faço ideia se fiz uma boa coisa, mas acho que gambiarrei valendo aqui ahahaha. Logo verás e dirás: "my eyeeees"

2024-01-02 23:42 UTC, ineBallardin commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +const PRODUCT_NAME_A = "Product A";
pq sim...
brincando...
Na verdade eu inicialmente achei q ia ter q usar no `describe` lá do `presenter`, mas criei um mock pq o teste em si era apenas pra verificar se o presenter tava realmente apresentando a saída no padrão correto e não necessariamente confirmar dados em si.

2024-01-02 23:50 UTC, arthurazevedofranca requested changes

2024-01-02 23:50 UTC, arthurazevedofranca commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +    const createProduct = async (name: string, price: number) => {
pq criou essa funcao so para usar no it de baixo? a funcao nao poderia ficar dentro do it pelo menos? se eu isolo a funcao do it para outro arquivo nao vai funcionar pq esta dependendo de um codigo fora sem contexto.
E precisa mesmo da funcao? nao vejo problema em repetir esse codigo. Inclusive ele se repete em outros its

2024-01-02 23:52 UTC, arthurazevedofranca commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +const PRODUCT_NAME_A = "Product A";
vou ponderar a mesma coisa do meu ultimo comentario. Se eu refator e acabo extraindo a funcao do describe para outro arquivo nao vai funcionar pois depende de variaveis no corpo desse arquivo... se for pensar nessa questao de dependencia e isolamento no paradigma funcional temos um code smell aqui ...

2024-01-02 23:54 UTC, arthurazevedofranca requested changes

2024-01-02 23:54 UTC, arthurazevedofranca commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +    it("should return the same output in both JSON and XML formats", async () => {
ta faltando assert com xml agora

2024-01-02 23:54 UTC, arthurazevedofranca commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +describe('ProductsPresenter', () => {
nao esquece do teste unitario do listJSON que criou agora

2024-01-04 20:53 UTC, ineBallardin commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +const PRODUCT_NAME_A = "Product A";
@arthurazevedofranca está corretíssimo, sr 🫡
Até já tinha trocado aqui, mas não mandei ainda. Logo mais eu mando.

2024-01-04 20:57 UTC, ineBallardin commented on src/infrastructure/api/presenters/products.presenter.ts
> +    static listXML(data: OutputListProductsDto): string {
Terá, se vc diz kkkkk

2024-01-04 21:08 UTC, ineBallardin commented on src/infrastructure/api/presenters/products.presenter.ts
> +    static listXML(data: OutputListProductsDto): string {
@arthurazevedofranca 
Pronto... finalmente... depois de dois dias kkkkk

2024-01-04 21:11 UTC, ineBallardin commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +    const createProduct = async (name: string, price: number) => {
é bom ter vastas opções HAHAHAHA
vai q cola, né?!

2024-01-04 21:17 UTC, ineBallardin commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +    const createProduct = async (name: string, price: number) => {
@arthurazevedofranca, vou deixa a função tá? Ou vc faz mta questão q ela suma? Vê aí como q tá agr...

2024-01-04 22:04 UTC, ineBallardin commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +    it("should return the same output in both JSON and XML formats", async () => {
Eu criei o testezinho p XML e vc vai ver q eu criei novamente os produtos aqui (e aí to usando a função hahahahaha). Pq antes na linha 8 estava usando o beforeAll, e aí eu tinha que rodar todo o teste pra saber se um it tava funcionando, resolvi mudar pra beforeEach pra testar isoladamente limpo de qq resquício dos outros testes e se um teste precisar ser atualizado ou removido, é menos provável que afete outros testes.. Mas né, não sei se isso é bom ou ruim. Vc q vai dizer kkkkkkkkk

2024-01-04 22:13 UTC, ineBallardin commented on src/infrastructure/api/__tests__/products.e2e.spec.ts
> +describe('ProductsPresenter', () => {
criei no products.presenter.test.ts

2024-01-04 22:24 UTC, ineBallardin commented on src/infrastructure/api/routes/products.route.ts
> +export const productsRoute = express.Router();
Não sei se entendi mto bem. Eu criei uma função que retorna o router e lá no express.ts chamei ela no app.use("/products", createProductsRoute());
Era isso msm?

2024-01-04 22:31 UTC, ineBallardin commented on src/infrastructure/api/routes/products.route.ts
> +        xml: async () => res.send(ProductsPresenter.listXML(output))
pq a resposta já tá vindo com json por padrão, temos um listXML pq converemos p XML depois e aí eu acabei criando um listJSON q reconverte o JSON convertido de volta p JSON kkkkkkkk

2024-01-04 22:35 UTC, ineBallardin commented on src/infrastructure/api/routes/products.route.ts
> +    const products = new CreateProductUseCase(new ProductRepository());
não entendi, eu já tô usando o usecase de products aqui.

2024-01-04 22:39 UTC, ineBallardin commented on src/infrastructure/api/routes/products.route.ts
> +    const listProducts = new ListProductUseCase(new ProductRepository());
veja se era isso q vc quis dizer

2024-01-17 18:14 UTC, merged